import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { format } from 'date-fns';

// Extend jsPDF with autoTable for TypeScript
declare module 'jspdf' {
  interface jsPDF {
    autoTable: any;
  }
}

export interface ReceiptData {
  receiptNo: string;
  date: string;
  tenantName: string;
  propertyName: string;
  propertyAddress: string;
  amount: number;
  monthYear: string;
  paymentMode: string;
  notes?: string;
  gstAmount?: number;
  gstNumber?: string;
  tdsAmount?: number;
  convenienceFee?: number;
}

export interface InvoiceData {
  invoiceNo: string;
  date: string;
  ownerName: string;
  propertyName: string;
  tenantName: string;
  commissionType: string;
  commissionValue: number;
  computedAmount: number;
  dealDate: string;
  notes?: string;
}

export class PDFGenerator {
  private static brandColor = [67, 56, 202]; // Primary Indigo
  private static secondaryColor = [71, 85, 105]; // Slate 600

  private static addHeader(doc: jsPDF, title: string) {
    // Brand Header
    doc.setFillColor(this.brandColor[0], this.brandColor[1], this.brandColor[2]);
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('RentMyWay', 20, 20);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Professional Property Management CRM', 20, 30);
    
    doc.setFontSize(18);
    doc.text(title.toUpperCase(), 190, 25, { align: 'right' });
  }

  private static addFooter(doc: jsPDF) {
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(
        `Generated by RentMyWay CRM on ${format(new Date(), 'dd MMM yyyy HH:mm')} | Page ${i} of ${pageCount}`,
        105,
        285,
        { align: 'center' }
      );
    }
  }

  static generateRentReceipt(data: ReceiptData) {
    const doc = new jsPDF();
    this.addHeader(doc, 'Rent Receipt');

    // Content Box
    doc.setTextColor(50);
    doc.setFontSize(12);
    
    // Receipt Details
    doc.setFont('helvetica', 'bold');
    doc.text('Receipt No:', 20, 60);
    doc.setFont('helvetica', 'normal');
    doc.text(data.receiptNo, 50, 60);
    
    doc.setFont('helvetica', 'bold');
    doc.text('Date:', 140, 60);
    doc.setFont('helvetica', 'normal');
    doc.text(data.date, 160, 60);

    // Main Content
    const tableBody: any[][] = [
      ['Received From', data.tenantName],
      ['Property', data.propertyName],
      ['Address', data.propertyAddress],
      ['For Month/Year', data.monthYear],
      ['Payment Mode', data.paymentMode.toUpperCase()]
    ];

    let totalAmount = data.amount;

    if (data.convenienceFee && data.convenienceFee > 0) {
      tableBody.push(['Convenience Fee', `INR ${data.convenienceFee.toLocaleString('en-IN')}`]);
      totalAmount += data.convenienceFee;
    }

    if (data.gstAmount && data.gstAmount > 0) {
      tableBody.push(['GST (18%)', `INR ${data.gstAmount.toLocaleString('en-IN')}`]);
      if (data.gstNumber) {
        tableBody.push(['GSTIN', data.gstNumber]);
      }
    }

    if (data.tdsAmount && data.tdsAmount > 0) {
      tableBody.push(['TDS Deducted', `INR ${data.tdsAmount.toLocaleString('en-IN')}`]);
      // TDS is usually deducted from total, so let's just show it, 
      // but amount paid is usually the net amount. 
      // Assuming data.amount is the base rent paid.
    }

    tableBody.push(['Total Amount Paid', `INR ${totalAmount.toLocaleString('en-IN')}`]);

    doc.autoTable({
      startY: 75,
      head: [['Description', 'Details']],
      body: tableBody,
      theme: 'striped',
      headStyles: { fillColor: this.brandColor },
      columnStyles: { 0: { fontStyle: 'bold', width: 50 } },
    });

    if (data.notes) {
      const finalY = (doc as any).lastAutoTable.finalY || 150;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text('Notes:', 20, finalY + 15);
      doc.setFont('helvetica', 'normal');
      doc.text(data.notes, 20, finalY + 22, { maxWidth: 170 });
    }

    // Signatures
    const finalY = (doc as any).lastAutoTable.finalY + 50;
    doc.setDrawColor(200);
    doc.line(20, finalY, 70, finalY);
    doc.line(140, finalY, 190, finalY);
    
    doc.setFontSize(10);
    doc.text('Authorized Signatory', 45, finalY + 5, { align: 'center' });
    doc.text('Receiver\'s Signature', 165, finalY + 5, { align: 'center' });

    this.addFooter(doc);
    doc.save(`Receipt_${data.receiptNo}.pdf`);
  }

  static generateLeasePDF(lease: any) {
    const doc = new jsPDF();
    this.addHeader(doc, 'Lease Agreement');

    doc.setTextColor(50);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('RESIDENTIAL LEASE AGREEMENT', 105, 55, { align: 'center' });

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    
    // Main Body Agreement clauses
    const clauses = [
      `This Residential Lease Agreement is entered into on ${format(new Date(lease.start_date), 'dd MMM yyyy')} by and between the Landlord / Broker, and the Tenant: ${lease.tenant?.name || 'Tenant'}.`,
      `1. LEASED PREMISES: The Landlord agrees to lease to the Tenant the property located at: ${lease.property?.title || 'Property Address'}, Locality: ${lease.property?.locality || 'N/A'}, City: ${lease.property?.city || 'N/A'}.`,
      `2. LEASE TERM: The lease shall commence on ${format(new Date(lease.start_date), 'dd MMM yyyy')} and expire on ${format(new Date(lease.end_date), 'dd MMM yyyy')} (unless terminated earlier in accordance with this agreement).`,
      `3. RENT PAYMENT: The monthly rent payable by the Tenant is INR ${lease.monthly_rent.toLocaleString('en-IN')}/month. Rent must be paid in full on or before the due date each month.`,
      `4. SECURITY DEPOSIT: The Tenant has deposited a security amount of INR ${lease.security_deposit.toLocaleString('en-IN')} as a security deposit. This deposit will be returned within 30 days of move-out, minus any deductions for damages or unpaid utilities.`,
      `5. LOCK-IN PERIOD & NOTICE: A mandatory lock-in period of ${lease.lock_in_months || 0} months applies from the commencement date. Following the lock-in period, either party may terminate this agreement by giving a written notice of ${lease.notice_period_days || 30} days.`,
      `6. UTILITIES & MAINTENANCE: The Tenant shall pay all utility bills (electricity, water, internet) promptly. Common area society maintenance charges are ₹${(lease.maintenance_charge || 0).toLocaleString('en-IN')}/mo.`,
      `7. COMPLIANCE & REPAIRS: The Tenant agrees to keep the premises in a good, clean condition and comply with all residential housing society regulations. Any structural repairs remain the responsibility of the Landlord.`
    ];

    let currentY = 70;
    for (const clause of clauses) {
      const splitClause = doc.splitTextToSize(clause, 170);
      doc.text(splitClause, 20, currentY);
      currentY += (splitClause.length * 5) + 8;
      
      // Page break check
      if (currentY > 260) {
        doc.addPage();
        this.addHeader(doc, 'Lease Agreement');
        currentY = 55;
      }
    }

    // Signatures
    currentY = Math.min(currentY + 20, 240);
    doc.setDrawColor(200);
    doc.line(20, currentY, 70, currentY);
    doc.line(140, currentY, 190, currentY);
    
    doc.setFontSize(10);
    doc.text('Tenant\'s Signature', 45, currentY + 5, { align: 'center' });
    doc.text('Broker / Owner Signature', 165, currentY + 5, { align: 'center' });

    this.addFooter(doc);
    doc.save(`Lease_Agreement_${lease.id.slice(0, 8)}.pdf`);
  }

  static generateCommissionInvoice(data: InvoiceData) {
    const doc = new jsPDF();
    this.addHeader(doc, 'Commission Invoice');

    doc.setTextColor(50);
    doc.setFontSize(12);
    
    doc.setFont('helvetica', 'bold');
    doc.text('Invoice No:', 20, 60);
    doc.setFont('helvetica', 'normal');
    doc.text(data.invoiceNo, 50, 60);
    
    doc.setFont('helvetica', 'bold');
    doc.text('Date:', 140, 60);
    doc.setFont('helvetica', 'normal');
    doc.text(data.date, 160, 60);

    doc.autoTable({
      startY: 75,
      head: [['Description', 'Details']],
      body: [
        ['Owner/Payee', data.ownerName],
        ['Property', data.propertyName],
        ['Tenant', data.tenantName],
        ['Commission Basis', data.commissionType.replace(/_/g, ' ').toUpperCase()],
        ['Rate/Value', data.commissionValue.toString()],
        ['Total Invoice Amount', `INR ${data.computedAmount.toLocaleString('en-IN')}`],
      ],
      theme: 'grid',
      headStyles: { fillColor: this.brandColor },
      columnStyles: { 0: { fontStyle: 'bold', width: 60 } },
    });

    const finalY = (doc as any).lastAutoTable.finalY + 20;
    doc.setFontSize(10);
    doc.text('Please process the payment at your earliest convenience.', 20, finalY);

    this.addFooter(doc);
    doc.save(`Invoice_${data.invoiceNo}.pdf`);
  }

  static generateOwnerStatement(ownerName: string, month: string, data: {
    income: number,
    expenses: number,
    payouts: any[],
    expenseList: any[],
    rentList: any[]
  }) {
    const doc = new jsPDF();
    this.addHeader(doc, 'Owner Statement');

    doc.setTextColor(50);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(`Statement for: ${ownerName}`, 20, 55);
    doc.text(`Period: ${month}`, 190, 55, { align: 'right' });

    // Summary Box
    doc.autoTable({
      startY: 65,
      head: [['Summary', 'Amount (INR)']],
      body: [
        ['Total Rent Collected', data.income.toLocaleString('en-IN')],
        ['Total Expenses/Deductions', `-${data.expenses.toLocaleString('en-IN')}`],
        ['Net Payout Disbursed', (data.income - data.expenses).toLocaleString('en-IN')],
      ],
      theme: 'grid',
      headStyles: { fillColor: this.brandColor },
      columnStyles: { 0: { fontStyle: 'bold' }, 1: { halign: 'right' } },
    });

    let currentY = (doc as any).lastAutoTable.finalY + 15;

    // Detailed Rent Collections
    doc.setFontSize(12);
    doc.text('Detailed Rent Collections', 20, currentY);
    doc.autoTable({
      startY: currentY + 5,
      head: [['Date', 'Description', 'Amount']],
      body: data.rentList.map(r => [
        format(new Date(r.payment_date), 'dd MMM yyyy'),
        `Rent for ${r.month_year}`,
        r.amount.toLocaleString('en-IN')
      ]),
      theme: 'striped',
      headStyles: { fillColor: this.secondaryColor },
    });

    currentY = (doc as any).lastAutoTable.finalY + 15;

    // Expenses
    if (data.expenseList.length > 0) {
      doc.text('Detailed Expenses', 20, currentY);
      doc.autoTable({
        startY: currentY + 5,
        head: [['Date', 'Category', 'Description', 'Amount']],
        body: data.expenseList.map(e => [
          format(new Date(e.date), 'dd MMM yyyy'),
          e.category.replace(/_/g, ' ').toUpperCase(),
          e.notes || 'N/A',
          e.amount.toLocaleString('en-IN')
        ]),
        theme: 'striped',
        headStyles: { fillColor: [185, 28, 28] }, // Red for expenses
      });
    }

    this.addFooter(doc);
    doc.save(`Statement_${ownerName.replace(/\s+/g, '_')}_${month.replace(/\s+/g, '_')}.pdf`);
  }
}
